name: Build

on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository to the runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Lint
      - name: Run Lint
        run: |
          npm run lint
